random_forest:
  n_estimators: 100  # Number of trees in the forest
  criterion: "gini"  # Split criterion: "gini" or "entropy"
  max_depth: 10  # Maximum depth of each tree (None means nodes are expanded until pure)
  min_samples_split: 2  # Minimum samples required to split a node
  min_samples_leaf: 1  # Minimum samples required in a leaf node
  max_features: "sqrt"  # Number of features to consider for best split ("sqrt" or "log2")
  bootstrap: True  # Whether bootstrap samples are used when building trees
  random_state: 42  # Ensures reproducibility
  n_jobs: -1  # Use all available CPU cores
  verbose: 0  # Set to 1 for more training output
  class_weight: "balanced"  # Adjust class weights (useful for imbalanced datasets)
