apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit-app
  ports:
    - protocol: TCP
      port: 80      # External port
      targetPort: 8501  # Container port (matches the deployment)
  type: NodePort  # Exposes the app on a port accessible on the minikube node
